### ISSUE TITLE
不知道会出Node.js版本吗？

### ISSUE THREAD

**Issue by lanbomo** [TommyLemon/APIJSON#10]
不知道会出Node.js版本吗？如果能出的话就太好了，这样前端开发人员就可以直接使用了。
希望作者能考虑一下。
谢谢！

**Comment by TommyLemon** [comment]
@lanbomo 有这个打算，nodejs接口开发我做过一段时间，不过没做过初始化配置这些工作，可能会踩一些坑

**Comment by jackyon** [comment]
+1

**Comment by TEsTsLA** [comment]
@TommyLemon 你应该向尤雨溪（Vue.js框架的作者）学习如何运营，大打爱国牌，挤压和诽谤其他的框架，顺理成章的拉更多的人入坑，然后登上人生巅峰

**Comment by TommyLemon** [comment]
@TEsTsLA Vue.js作者真是这样的人吗？我觉得[Vue.js在官网与React和Anjular的对比](https://cn.vuejs.org/v2/guide/comparison.html)挺中肯的啊，另外我也没看到作者 打爱国牌，挤压和诽谤其他的框架 啊

**Comment by TEsTsLA** [comment]
你看他和angular的布道者大漠穷秋之间的撕逼不就可以猜个一二吗

**Comment by TommyLemon** [comment]
这么一说，我好像去年是在知乎上看到过他怼大漠穷秋，在一个贬低Vue的问题下。我早期只知道有Vue是前端3大框架之一，因为我不做前端就没太大的兴趣，后来是公司用了我才和前端的同事一起边学边用的，双向绑定很赞，我做Android开发都是要写大量的绑定View的代码，DataBinding虽然也支持双向绑定，但用起来比较别扭，还需要一装插件

**Comment by yuu2lee4** [comment]
@TommyLemon  node实现啥时候出呢，毕竟现在java还是做得比较底层的服务，跟前端对接的还是php、node这些比较多

**Comment by TommyLemon** [comment]
@yuu2lee4 你这么说显然就是用Node做中间件，后端用了APIJSON后就不需要中间件了。
中间件是为了解决后端API提供的数据和结构不能很好地满足前端的需求，但APIJSON能让前端完全定制数据和结构，也就是能很好地满足前端的需求，就没必要加一个中间件去对API做各种聚合、对结构做各种变换了。
具体可以看我在知乎的回答
https://www.zhihu.com/question/264563447/answer/434112510

**Comment by yuu2lee4** [comment]
就算这样 也不能忽视现在大量中小型创业公司都是用的php、node之类的做后端

**Comment by TommyLemon** [comment]
@yuu2lee4 如果是做后端，那确实有必要实现了。
我对Node不是很熟，暂时也没时间和精力去开发，希望有热心的开发者做出来哈。
[C#版](https://github.com/liaozb/APIJSON.NET) 已经出来了，
[Node版](https://github.com/TommyLemon/APIJSON/issues/6) 还不清楚进度，你可以问问楼主。

如何实现其它语言的APIJSON？
https://github.com/TommyLemon/APIJSON/issues/38

**Comment by figozhu** [comment]
node.js目前不太现实，因为JavaScript现在还不支持注解

**Comment by TommyLemon** [comment]
@figozhu 
目前APIJSON只有自动化权限管理才需要注解
https://my.oschina.net/tommylemon/blog/889074

注解也只是为了配置，其实换成非注解的代码也可以的。

我打算放到数据库了，服务启动时一次全加载并缓存，后续通过接口来更新缓存，
这样不但不用写代码配置更方便，还能自动生成文档、支持热部署。

**Comment by hqzh** [comment]
@TommyLemon 请问下这是你个人的开源还是公司的,会一直维护下去吗?

**Comment by TommyLemon** [comment]
@hqzh 个人开源的，先开源后投入公司项目使用，这个是我从16年开始就一直在维护的核心项目，也会一直维护下去

**Comment by TommyLemon** [comment]
@lanbomo @jackyon @yuu2lee4 @figozhu 
APIJSON Node.js 版，基于 [ypeorm](https://github.com/typeorm/typeorm) ，使用 TypeScript 实现。

创作不易，给热心的作者右上角点 ⭐Star 支持下吧 ^_^ 
https://github.com/TEsTsLA/apijson

**Comment by TommyLemon** [comment]
@lanbomo @jackyon @yuu2lee4 @figozhu 
另一个 APIJSON Node 版本也出来了，
支持单表、关联、数组、分页查询等，有比较完善的文档，
我测试过，除了项目提供的表有 utf8 编码问题导入不了 (用我自己的表测试可以），其它都可用。
作者是微医的，已经写了不少测试用例，在他公司内部用起来了。

点 Star 鼓励作者继续完善吧 ^_^
https://github.com/kevinaskin/apijson-node
