### ISSUE TITLE
What

### ISSUE THREAD

**Issue by wellorange** [TommyLemon/APIJSON#15]
这不就是graphql吗

**Comment by TommyLemon** [comment]
@wellorange 概念接近，实际实现和使用差别很大
https://github.com/TommyLemon/APIJSON/issues/2

**Comment by wellorange** [comment]
重复造轮子，你这玩意是为了解决什么问题而产生的呢！graphql不是为了解决沟通协议的问题，一个新的技术存在肯定是为了解决某个问题而存在的，所以我才说你，还是给个start因为你对graphql很熟悉

**Comment by TommyLemon** [comment]
@wellorange 

为什么要用APIJSON？或者APIJSON有什么用？
https://github.com/TommyLemon/APIJSON/wiki

GraphQL只是半自动化，APIJSON是完全自动化
https://ruby-china.org/topics/31997
