### ISSUE TITLE
希望能够对demo提供一个文档

### ISSUE THREAD

**Issue by zhou-wjjw** [TommyLemon/APIJSON#17]
这两天详细看了APIJSON，demo也跑了，效果非常好，感谢开源奉献。自己想在开发中用的时候，却有一种无从下手的感觉（可能太菜了吧^^），包括整个执行的逻辑，自己应该重写哪些方法？希望提供一个文档，来说明一个这个demo的实现，如此愿意尝试朋友，一下子就明白了，都去看源码压力太大。
或者简单的提一下哪些类是干嘛的，我想在项目利用APIJSON写CURD，该去实现那几部分？

**Comment by zhou-wjjw** [comment]
懂了，懂了，真的够容易，太赞了，等我把这个项目搞完了，做成一个案例配上文档，commit一下。

**Comment by TommyLemon** [comment]
可以的，非常感谢
