### ISSUE TITLE
可不可以打包成jar

### ISSUE THREAD

**Issue by baikeqin** [TommyLemon/APIJSON#19]
可不可以打包成jar，不然去哪里下载jar

**Comment by TommyLemon** [comment]
@baikeqin 是指maven依赖的fastjson，springboot依赖包，还是说要把APIJSON-Java-Server整个工程打成jar呢？
如果是前者，那是自动下载的，开VPN翻墙的话下载会比较快。
如果是后者，我可以打一个APIJSONLibrary的jar包出来。

**Comment by baikeqin** [comment]
就是把你这个核心的东西做成jar，其他的东西都是可以在中央仓库下载的

**Comment by TommyLemon** [comment]
@baikeqin 可以的

**Comment by TommyLemon** [comment]
其实就是APIJSONLibrary，目前是通过依赖工程的方式，APIJSONDemo依赖APIJSONLibrary。
将APIJSONLibrary打成jar包后，放到APIJSONDemo的libs目录下，就不用依赖APIJSONLibrary工程了。
已经更新到APIJSON Github，欢迎使用^_^

**Comment by onlyfew** [comment]
我自己的springboot的项目，引入APIJSONORM后，运行没问题，但是用maven编译会报错。如何解决呢？

**Comment by TommyLemon** [comment]
Maven 里面配置依赖这个 jar

**Comment by TommyLemon** [comment]
@baikeqin @onlyfew APIJSON ORM 已支持 Maven, Gradle 等远程依赖方式，具体见
https://github.com/APIJSON/apijson-orm
