### ISSUE TITLE
将整个后台打成war包

### ISSUE THREAD

**Issue by symplaty** [TommyLemon/APIJSON#24]
你好，请问一下怎么将这整个后台打成war包放到服务器上，我试了很多方法，可以运行，但是打war包的时候找不到引用的apijson-library库

**Comment by TommyLemon** [comment]
APIJSON-Java-Server Demo是基于SpringBoot开发的，建议打成可运行的jar包，更方便使用，群里(607020115)有视频。
如果一定要war包，建议export时勾选上所有文件，包括apijson-server.jar，或者APIJSONDemo依赖APIJSONLibrary后，export时把APIJSONLibrary也勾选上。可以搜下SpringBoot打war包的教程。

**Comment by symplaty** [comment]
感谢，问题已经解决了。

**Comment by TommyLemon** [comment]
好的，解决方案可以分享下，帮助大家哈

**Comment by zemelLeong** [comment]
@symplaty 请问是怎么解决的呀
