### ISSUE TITLE
用于实现其他语言的 Server 端的 APIJSON 的规范文档能整一个吗

### ISSUE THREAD

**Issue by kikajack** [TommyLemon/APIJSON#25]
[这个](https://github.com/TommyLemon/APIJSON/blob/master/Document.md) 通用文档的 [设计规范](https://github.com/TommyLemon/APIJSON/blob/master/Document.md#3) 部分还是有点简洁了，对于其他语言的 Server 端开发，估计还是需要参考现有的 Java 实现。

**Comment by TommyLemon** [comment]
规范就这么多啊，原理就是将前端传的请求JSON转换为SQL语句，连接执行后返回JSON结果。
目前APIJSONDemo基于SpringBoot做了几个自动化的API，Controller接收到请求JSON后交给APIJSONLibrary这个ORM库的Parser解析，Parser再通过SQLConfig去生成SQL语句，最后返回给APIJSONDemo，APIJSONDemo里的SQLExecutor子类再连接数据库执行，最后按原路径返回JSON结果。
这是实现原理的比较详细的说明
https://github.com/TommyLemon/APIJSON/issues/6

**Comment by TommyLemon** [comment]
NodeJS建议用koa2做中间件，相当于Java的SpringBoot，然后再将JSON转换为SQL语句

**Comment by zeromake** [comment]
@TommyLemon 我自己写个一个类似的python的，用的SQLAlchemy通过json生成sql，现在有点烦自己设计规范。要不我把 APIJSON 规范抄了吧。

**Comment by TommyLemon** [comment]
@zeromake 可以啊

**Comment by zeromake** [comment]
@TommyLemon 看了一下实现规范说明有点杂乱。我现在的规范是抄的 [leancloud](https://leancloud.cn/docs/rest_api.html)。

**Comment by TommyLemon** [comment]
[设计规范](https://github.com/TommyLemon/APIJSON/blob/master/Document.md#3) 不是实现规范，而是对于达到某种效果的描述哦，具体怎么实现可不管，所以才能不局限于某种语言，目前因为我个人能力和精力问题，所以只实现了Java版的Server。

APIJSON协议的核心就是 引用赋值 ，它是实现对象之间关系描述的功能，对于MySQL，Oracle，MSSQL Server等关系型数据库非常适用，也是最难实现的部分。其它功能都是SQL语法用key:value表示的简单对应描述，实现也比较简单。

APIJSON的实现原理请参考
https://github.com/TommyLemon/APIJSON/issues/6

如果你开发出来，我甚至还可以帮你推广下^_^

**Comment by TommyLemon** [comment]
支持啊，
http://apijson.cn:8080/get
```js
{
    "User[]": {
        "count": 10, // LIMIT 0, 10
        "User": {
            "@column": "id,name", // SELECT id,name
            "name": "APIJSONUser", // WHERE name = 'APIJSONUser'
            "name$": "A%", // WHERE name LIKE 'A%'
            "id!": 38710, // WHERE id !=  '38710'
            "id{}": [  // WHERE id IN  ('1490109742863', '1490109845208', '1490420651686', '1493748615711')
                1490109742863,
                1490109845208,
                1490420651686,
                1493748615711
            ],
            "id!{}": [  // WHERE id NOT IN  ('1490584952968', '1492936169722')
                1490584952968,
                1492936169722
            ]
        }
    }
}
```
返回：
```js
{
    "User[]": [
        {
            "id": 1490109742863,
            "name": "APIJSONUser"
        },
        {
            "id": 1490109845208,
            "name": "APIJSONUser"
        },
        {
            "id": 1490420651686,
            "name": "APIJSONUser"
        },
        {
            "id": 1493748615711,
            "name": "APIJSONUser"
        }
    ],
    "code": 200,
    "msg": "success"
}
```

**Comment by TommyLemon** [comment]
@zeromake 
![apijson_function](https://user-images.githubusercontent.com/5738175/40278104-872c6250-5c5d-11e8-96b0-184084cdbc85.jpg)

**Comment by zeromake** [comment]
@TommyLemon 我考虑下，研究套json api对应抽象数据库操作的说明，再考虑实现，我现在的用的是 `leancloud` 的规范，要改成 `APIJSON` 也不难。好像没有看到 `OR`, `AND` 的对照 json 表现模式？

**Comment by TommyLemon** [comment]
@zeromake APIJSON 不是 JSON API哦。
OR - | 或不写
AND - &
NOT - !
见功能符中的 [逻辑运算](https://github.com/TommyLemon/APIJSON/blob/master/Document.md#3.2)

**Comment by TommyLemon** [comment]
@zeromake 好吧，上图就是了

**Comment by mlick** [comment]
就是想进来说下，很腻害！

**Comment by TommyLemon** [comment]
[如何实现其它语言的APIJSON？](
https://github.com/TommyLemon/APIJSON/issues/38)
