### ISSUE TITLE
未做任何防止注入的实现，可轻松删库删表

### ISSUE THREAD

**Issue by dh454981620** [TommyLemon/APIJSON#26]
跑了一下项目可以轻松注入sql删库删表
比如：
{
"xxx[]":{
  "count":5,
  "page":0,
  "query":0,
  "xxx":{
  "@column":"* FROM xxx_info;delete from xxx --  "
  }
}
}
此BUG严重！未修复前不建议使用，或者自行修改代码

**Comment by TommyLemon** [comment]
@dh454981620  您好，感谢您的提醒，不过您给的这个示例经过测试并没有做到删库、删表其中任何一个哦。
能否留下联系方式，或者加我QQ 1184482681，我们再具体沟通下？

![74d36d37-2e3f-4008-8e93-457013bd9126](https://user-images.githubusercontent.com/5738175/39953321-bc76f656-55db-11e8-8744-0f38099357d1.png)


![906af7d2-ffde-4a53-b6aa-206bab4b22c2](https://user-images.githubusercontent.com/5738175/39953278-aa382768-55da-11e8-89ee-8c72bbc9cd44.png)

Server日志：
AbstractParser.DEBUG: 



<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
GET/parseResponse  request = 
{"xxx[]":{"count":5,"page":0,"query":0,"xxx":{"@column":"* FROM xxx_info;delete from xxx -- "}}}


AbstractParser.DEBUG: parseResponse  startTime = 1526097413407<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


 
ObjectParser.DEBUG: ObjectParser  table = null; isTable = false
ObjectParser.DEBUG: ObjectParser  isEmpty = false; tri = false; drop = false
AbstractParser.DEBUG: getArray  query = 0; count = 5; page = 0
AbstractParser.DEBUG: getArray  size = 5; page = 0
ObjectParser.DEBUG: ObjectParser  table = 0; isTable = false
ObjectParser.DEBUG: ObjectParser  isEmpty = false; tri = false; drop = false
ObjectParser.DEBUG: ObjectParser  table = xxx; isTable = false
ObjectParser.DEBUG: ObjectParser  isEmpty = false; tri = false; drop = false
ObjectParser.DEBUG: ObjectParser  table = 1; isTable = false
ObjectParser.DEBUG: ObjectParser  isEmpty = false; tri = false; drop = false
ObjectParser.DEBUG: ObjectParser  table = xxx; isTable = false
ObjectParser.DEBUG: ObjectParser  isEmpty = false; tri = false; drop = false
ObjectParser.DEBUG: ObjectParser  table = 2; isTable = false
ObjectParser.DEBUG: ObjectParser  isEmpty = false; tri = false; drop = false
ObjectParser.DEBUG: ObjectParser  table = xxx; isTable = false
ObjectParser.DEBUG: ObjectParser  isEmpty = false; tri = false; drop = false
ObjectParser.DEBUG: ObjectParser  table = 3; isTable = false
ObjectParser.DEBUG: ObjectParser  isEmpty = false; tri = false; drop = false
ObjectParser.DEBUG: ObjectParser  table = xxx; isTable = false
ObjectParser.DEBUG: ObjectParser  isEmpty = false; tri = false; drop = false
ObjectParser.DEBUG: ObjectParser  table = 4; isTable = false
ObjectParser.DEBUG: ObjectParser  isEmpty = false; tri = false; drop = false
ObjectParser.DEBUG: ObjectParser  table = xxx; isTable = false
ObjectParser.DEBUG: ObjectParser  isEmpty = false; tri = false; drop = false
AbstractParser.DEBUG: 



<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
 GET/parseResponse  request = 
{"xxx[]":{"count":5,"page":0,"query":0,"xxx":{"@column":"* FROM xxx_info;delete from xxx -- "}}}


AbstractParser.DEBUG: parse  return response = 
{"xxx[]":[{"@column":"* FROM xxx_info;delete from xxx -- "},{"@column":"* FROM xxx_info;delete from xxx -- "},{"@column":"* FROM xxx_info;delete from xxx -- "},{"@column":"* FROM xxx_info;delete from xxx -- "},{"@column":"* FROM xxx_info;delete from xxx -- "}],"code":200,"msg":"success"}
 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 



AbstractParser.DEBUG: parseResponse  endTime = 1526097413407;  duration = 0>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by TommyLemon** [comment]
已全面防SQL注入，请下载最新版
https://github.com/TommyLemon/APIJSON/releases/tag/2.4.0
