### ISSUE TITLE
完全不知道这个东西究竟解决了什么核心问题。。。

### ISSUE THREAD

**Issue by NicolJiang** [TommyLemon/APIJSON#28]
如果我没理解错的话，为了极少的部分场景，却滋生了很多新的问题。

**Comment by TommyLemon** [comment]
解决了沟通和开发效率等问题。
所有需要对接的地方，沟通问题都是最大的问题。

为什么要用APIJSON？前后端9大痛点解析
https://github.com/TommyLemon/APIJSON/wiki

请问对于一个网站或客户端App，前端调接口的场景难道是极少的？后端对数据库增删改查的场景难道不是占绝大部分业务代码？
APIJSON让后端不用写接口、也不用写文档就能提供"接口"和"文档"，前端/客户端不用看"文档"就能调用"接口"。

至于新的问题，请用事实举例谢谢

**Comment by NicolJiang** [comment]
你列的 9 大痛点，都是「流程 / 规范」上的痛点。。。

**Comment by TommyLemon** [comment]
难道这就不是痛点？解决了痛点不好吗？能用技术低成本解决的问题，非得用高成本的管理来死磕？

而且APIJSON的适用范围也在主页说得很清楚了：
适合中小型前后端分离的项目，尤其是互联网创业项目和企业自用项目。

你能指望一大堆小公司在流程/规范上做好吗？开发都是不停地赶需求，连文档都没时间好好写。
大公司就忽略掉吧，APIJSON并不是为它们开发的。

**Comment by wanghaisheng** [comment]
@NicolJiang 有多钱有能人 不需要看这个东西 
资源不足 楼主的东西就很大程度上可以降低成本了
一切都是权衡取舍 没必要纠结是白猫黑猫

**Comment by NightFarmer** [comment]
借楼吐槽一下  
在gank上看到的 乍一看好像很牛逼的东西 以为是给客户端用的框架   
readme翻来覆去看了几遍才发现不是，而是给后台用的东西  
感觉作者的思路或许是这样的
```
调接口好烦，不如传个sql给后台查完返给我吧。
↓
传sql好像不怎么安全，不如定义一套语法来做限制。
↓
那后台好像要相应的参数解析了，开搞。
↓
像那么回事了，不如加一些东西让它能满足更多的场景吧，权限防注入其他的也就加上了
↓
成品
```
这个本质上还是传sql啊。

**Comment by TommyLemon** [comment]
@NightFarmer 
我也不知gank的编辑为啥只放了Android端的效果图。
APIJSON-Android用了我的 [Android快速开发框架ZBLibrary](https://github.com/TommyLemon/Android-ZBLibrary)

APIJSON是给前后端API通信用的，
所以不仅包括Java,C#,PHP,Python等后端，
也包括Andoird，iOS，Web前端等。

目前APIJSON后端有  Java，C# 版实现，Python正在开发中；
前端（客户端）有Andoird，iOS，JavaScript实现。

你说的思路基本符合我当时的情况。
但传SQL不仅仅是 因为解析困难导致 安全及权限问题难以解决，
还不能直观地通过Request JSON来看出Response JSON的结构，
![](https://raw.githubusercontent.com/TommyLemon/StaticResources/master/APIJSON_Auto_get.jpg)

更不用说 提取字段、远程函数 等功能了。
https://github.com/TommyLemon/APIJSON/blob/master/Document.md#3.2

APIJSON 提供了自动化API、自动生成文档、自动化权限管理、自动校验请求、自动管理版本等，
很好的解决了前后端关于API的沟通与扯皮、开发流程长效率低等 各种头疼的问题

为什么要用APIJSON？或者APIJSON有什么用？
https://github.com/TommyLemon/APIJSON/wiki

**Comment by seek-x2y** [comment]
其实认真读读《RESTful Web APIs》这本书就差不多明白了，Web API 落后于 Web

**Comment by liupeng110** [comment]
建议这个issu重新打开并置顶.
@NightFarmer   总结的太到位了
这个开发流程是前端和后台一起制定数据库表吗
 或者说前端后台共用同一个bean

**Comment by TommyLemon** [comment]
> 建议这个issu重新打开并置顶.
> @NightFarmer 总结的太到位了
> 这个开发流程是前端和后台一起制定数据库表吗
> 或者说前端后台共用同一个bean
连 “这个开发流程是前端和后台一起制定数据库表吗“”或者说前端后台共用同一个bean” 这种话都说出来了，说明你根本不是知道 APIJSON 是啥
https://www.zhihu.com/question/432617493
