### ISSUE TITLE
楼主这个和prisma有什么不同，两个都不了解，求比较一下

### ISSUE THREAD

**Issue by zwl1619** [TommyLemon/APIJSON#29]
楼主这个和prisma有什么不同，两个都不了解，求比较一下：

https://github.com/prismagraphql/prisma

**Comment by TommyLemon** [comment]
Prisma是一个ORM库，用面向对象的方式实现SQL语句的封装。
需要后端针对每个需求都写封装SQL语句的代码哦
https://github.com/prismagraphql/prisma/blob/master/examples/application-server/generated-schema.graphql
```js
type Query {
  posts(where: PostWhereInput, orderBy: PostOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Post]!
  users(where: UserWhereInput, orderBy: UserOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [User]!
  post(where: PostWhereUniqueInput!): Post
  user(where: UserWhereUniqueInput!): User
  postsConnection(where: PostWhereInput, orderBy: PostOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): PostConnection!
  usersConnection(where: UserWhereInput, orderBy: UserOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): UserConnection!

  """Fetches an object given its ID"""
  node(
    """The ID of an object"""
    id: ID!
  ): Node
}
```

而APIJSON是完全自动化生成SQL语句的，后端不需要写相关代码。
文档上给出的表和字段随便试，任何结构任何数据都支持。
http://apijson.cn/

**Comment by TommyLemon** [comment]
@zwl1619  APIJSON Node 版本也出来了，语言一样，你可以具体对比下。
目前在初期阶段，用了 TypeORM，所以需要写 Model 类（Java 版不需要）。

apijson-node 支持单表、关联、数组、分页查询等，有比较完善的文档，
我测试过，除了项目提供的表有 utf8 编码问题导入不了 (用我自己的表测试可以），其它都可用。
作者是微医的，已经写了不少测试用例，在他公司内部用起来了。

点 Star 鼓励作者继续完善吧 ^_^
https://github.com/kevinaskin/apijson-node
