### ISSUE TITLE
服务器端禁止单个字段请求如何实现？

### ISSUE THREAD

**Issue by exment** [TommyLemon/APIJSON#31]
在java服务器端例子里面没有Operation相关的例子，例如DISALLOW如何使用。
现在项目要用到老表 user表里面有password字段等 能不能禁止客户端查询？

**Comment by TommyLemon** [comment]
Operation里面是后端对非开放请求（GET,HEAD）的操作，其中DISALLOW是不允许请求传的参数。
禁止查询可通过在字段名前加下划线解决，例如 Privacy里的 _password ， _payPassword .这样怎么都不会返回了

**Comment by TommyLemon** [comment]
或者在AbstractSQLExecutor.execute里result.put封装字段前拦截掉password等字段，目前里面已经拦截了 _key

**Comment by exment** [comment]
1如果字段前加_ 会改动原来的表，不能动。
2如果在AbstractSQLExecutor.execute里result.put修改总觉得不太好，又修改了library，又写死了代码。

**Comment by TommyLemon** [comment]
以后会在AbstractSQLExecutor内提供在一个 
```java
protected void onPutColumn(String column, String lable, Object value) {
  ...
}
```
方法，子类可重写
```java
@Override
protected void onPutColumn(String column, String lable, Object value) {
   if ("password".equals(column)) { //不返回password
      return;
   }
   super.onPutColumn(column, lable, value);
}
```
这样就不用改library代码了。

不过目前你还是用方法2吧，或者等我明天改下，你用新版。

**Comment by exment** [comment]
非常感谢！坐等更新~

**Comment by exment** [comment]
假设我有两张表都有password字段（重名字段），一张表能返回，一张表不能返回。。。

**Comment by TommyLemon** [comment]
判断 config.getTable()

**Comment by exment** [comment]
OK~

**Comment by TommyLemon** [comment]
好了，下载最新版，在DemoSQLExecutor重写onPutColumn
```java
	@Override
	protected JSONObject onPutColumn(SQLConfig config, ResultSet rs, ResultSetMetaData rsmd, int tablePosition,
			JSONObject table, int columnIndex) throws Exception {
		if ("Comment".equals(config.getTable()) && "content".equals(rsmd.getColumnName(columnIndex))) {
			return table;
		}
		return super.onPutColumn(config, rs, rsmd, tablePosition, table, columnIndex);
	}
```

**Comment by TommyLemon** [comment]
1.这里设置不返回Moment中的content字段

![c0d4fdb9-34f2-4ed6-abda-0b336e6b2910](https://user-images.githubusercontent.com/5738175/41473624-6c3ff85a-70ec-11e8-8cd0-a1a7de9f3c90.png)


2.用APIJSONAuto自动化接口回归测试，发现Moment相关的接口都被标记为 [缺少字段/整数变小数]

![b3ff0690-1236-4d0d-b754-18e54ab69804](https://user-images.githubusercontent.com/5738175/41473659-88d4750e-70ec-11e8-9cc6-cd07dec4a199.png)



3.用 [Beyond Compare](http://www.scootersoftware.com/) 对比从接口
   [V2 获取动态及发布者用户 /get]  
下载到的
  APIJSON自动化回归测试-前.txt
  APIJSON自动化回归测试-后.txt
两个文件，发现Moment比改之前少了content字段。


![b09d5d26-2aec-4aba-aae7-f3108dd35ccc](https://user-images.githubusercontent.com/5738175/41473719-ae237cec-70ec-11e8-914a-77fc3078279b.png)

**Comment by exment** [comment]
非常感谢，好棒~
