### ISSUE TITLE
怎么打包到Linux上运行

### ISSUE THREAD

**Issue by yeancai** [TommyLemon/APIJSON#32]
在本地运行起来了但是
想编译成jar放到服务器上运行
试了mvn compile 出错
百度后在里面增加了，我的目的是增加Lib带项目里面，不知道正确不，但是mvn compile成功了。
```
<dependency>
	<groupId>apijson-server</groupId>
	<artifactId>apijson-server</artifactId>
	<version>2.5.5</version>
	<scope>system</scope>
	<systemPath>${project.basedir}/libs/apijson-server2.5.5.jar
	</systemPath>
</dependency>
```
不过mvn package还是失败 - -  没接触过JAVA，忘能指点一二

**Comment by TommyLemon** [comment]
加群吧，群里有Eclipse打jar包的视频和Idea打jar包的聊天记录
607020115

**Comment by wangwei518** [comment]
视频够模糊，不过瞎蒙着搞定了，选项如下：
![I6{V1I5OZ2 FPJ)NMY%7K$O](https://user-images.githubusercontent.com/17971960/87240387-a818a480-c44b-11ea-88d5-454fa412addb.png)
![ZYZ`3O1L_%)Y~{T~Q 3GNIB](https://user-images.githubusercontent.com/17971960/87240397-bff02880-c44b-11ea-9076-82747e51794a.png)

**Comment by TommyLemon** [comment]
@wangwei518 👍
