### ISSUE TITLE
访问数据库定死了用mysql，还是drivermanager不是datasource的

### ISSUE THREAD

**Issue by rainmanhhh** [TommyLemon/APIJSON#34]
这有点太暴力了吧

**Comment by TommyLemon** [comment]
目前确实只有 MySQL 的 [AbstractSQLConfig](https://github.com/TommyLemon/APIJSON/blob/4dc97ede88e9a6222e0b0da8b61eefad3e3d8372/APIJSON-Java-Server/APIJSONLibrary/src/main/java/zuo/biao/apijson/server/AbstractSQLConfig.java) ，你需要哪个数据库的呢？

[DemoSQLExecutor](https://github.com/TommyLemon/APIJSON/blob/75227ad57aea7dd5c4eab3fc5a7e552e8f4dc673/APIJSON-Java-Server/APIJSONDemo/src/main/java/apijson/demo/server/DemoSQLExecutor.java) 主要用于展示 [APIJSONLibrary](https://github.com/TommyLemon/APIJSON/tree/4dc97ede88e9a6222e0b0da8b61eefad3e3d8372/APIJSON-Java-Server) 的用法，所以用了比较基础的 DriverManager ，这个开发者可以完全自己定制哈。

**Comment by molysama** [comment]
与其说是框架，不如说是工具

**Comment by TommyLemon** [comment]
@rainmanhhh  
Java版Server已支持 PostgreSQL，可通过 "@database": "PostgreSQL" 指定数据库类型。
https://github.com/TommyLemon/APIJSON/tree/master/APIJSON-Java-Server

C#版(使用SqlSuger)支持 MySQL, Oracle, MS SQL Server, PostgreSQL, SQLite
https://github.com/liaozb/APIJSON.NET

感谢支持，给热心的作者点Star支持下吧^_^

**Comment by TommyLemon** [comment]
Java版Server已支持 Oracle
https://github.com/TommyLemon/APIJSON/tree/master/APIJSON-Java-Server

**Comment by TommyLemon** [comment]
@qiushangzhe  apijson-mongodb，NoSQL 数据库 MongoDB 的 APIJSON 插件
https://github.com/APIJSON/apijson-mongodb
<img width="1531" alt="image" src="https://github.com/Tencent/APIJSON/assets/5738175/36406e20-b157-4121-bca7-280491462481">
