### ISSUE TITLE
希望实现两张表 一对多 关联查询

### ISSUE THREAD

**Issue by Jeffsyl01** [TommyLemon/APIJSON#40]
目前APIJSON已经实现了实现如下的两张表 一对多 关联查询：
```js
{
    "Moment": {},
    "[]": {
        "Comment": {
            "momentId@": "Moment/id"
        }
    }
}
```
但是如果我想查询Moment和Moment的praiseUserIdList对应的User，就不行了：
```js
{
    "Moment": {},
    "[]": {
        "User": {
            "id@": "[]/Moment/praiseUserIdList"
        }
    }
}
```

**Comment by TommyLemon** [comment]
已经实现了，你的方式错了
User.id 和 Moment.praiseUserIdList 的关系是 id 在 praiseUserIdList 里面：
```js
"id{}": praiseUserIdList 
```
因为 praiseUserIdList  的值是不确定的，可以通过 引用赋值 来从 Moment 中取：
```js
"id{}@": "Moment/praiseUserIdList" // 按你上面的写法，[]里面都没有Moment，所以找不到
```
最终就是：
```js
{
    "Moment": {},
    "[]": {
        "User": {
            "id{}@": "Moment/praiseUserIdList"
        }
    }
}
```

**Comment by Jeffsyl01** [comment]
十分感谢

**Comment by zhanghaicheng1** [comment]
提问：如果User.id 和 Moment.praiseUserIdList 的关系是 id **_相等_** praiseUserIdList ，而不是id in praiseUserIdList？
通过id和praiseUserIdList关联，怎么获取其他多条记录呢？我这边是如下图错误
![image](https://user-images.githubusercontent.com/46189785/121496130-c3e64b00-ca0c-11eb-9d27-c7a207f45597.png)

**Comment by TommyLemon** [comment]
把多余 "{}" 去掉，这是 IN 的语法，看文档
https://github.com/Tencent/APIJSON/blob/master/Document.md#3.2
