### ISSUE TITLE
[接口问题] count 参数名前面建议加 @

### ISSUE THREAD

**Issue by zhangchunlin** [TommyLemon/APIJSON#51]
```
{
  "[]":{
    "count":3,             //只要3个
    "User":{
      "@column":"id,name"  //只要id,name这两个字段
    }
  }
}
```
这里建议改成 @count ，这样避免和表名重名 （我的python版是会支持表名小写的）

**Comment by TommyLemon** [comment]
count, page, query, join 都是对 数组内整个对象 而言的。
@count 这种如果在主表和副表都有，用哪个呢？都用各自的？
page, query, join 也分别对应地改为 @page, @query, @join ? a
这些本来都是统一的配置，不能分开放，放外层不仅能避免以上问题，还更简单明确

**Comment by zhangchunlin** [comment]
@TommyLemon 我已经放在外面了，我只是建议在 count 前面加 at 符号

**Comment by TommyLemon** [comment]
加不加都是能正常解析的，只要解析时用对应名称就行。
只是写起来还是不加更方便。
