### ISSUE TITLE
为何star那么多而issue那么少

### ISSUE THREAD

**Issue by star7th** [TommyLemon/APIJSON#53]
作为一个开发者，比较关心反馈问题。良好的反馈和解决问题的速度是决定用不用一个东西的关键。
但我发现这里反馈的问题很少，不知道实际使用情况如何。有没有类似的社区或者什么地方可以看到其他人使用情况

**Comment by TommyLemon** [comment]
1.issue 是一个公开的讨论区，可以发任何东西。
2.大部分issue都是 提交bug、提建议、提问题（如何使用XXX，怎么添加XXX，有没有文档 等），还有些是灌水、发泄 等。
3.issue 的数量和 Repo 的 受关注程度、使用频率、用户群体、Repo本身的代码与文档质量 等相关。

APIJSON 只有配置权限需要写代码，加上详细的文档、视频教程、测试工具，
已经做到非常简单易用了，所以很少有问“怎样配置XXX”，“如何部署XXX”之类的问题。

APIJSON 经过 2 年时间维护、1000+次 Commit、40+ 次 Release， 功能上已经很完善、稳定，
所以也很少有用户问“如何解决XXX”之类的问题。

还有 APIJSON 目前大部分用户都是 国内的开发者，他们更倾向于在首页提供的 QQ 群交流和讨论。

**Comment by TommyLemon** [comment]
APIJSON 的可靠性可以参考这个报告。
总共 10617 行代码，查出 16 个「可能」的 bug， 24 个改进建议，bugs/lines 高达 99.85% 。
https://github.com/TommyLemon/APIJSON/issues/48
