### ISSUE TITLE
返回内容的不是json头

### ISSUE THREAD

**Issue by 35924784** [TommyLemon/APIJSON#55]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**

返回内容的不是json头

**错误信息**

返回内容的不是json头

**Comment by 35924784** [comment]
最终在get上增加了Produces，响应头就正常了。
<img width="670" alt="default" src="https://user-images.githubusercontent.com/5801601/49586348-e01c5380-f99b-11e8-8429-615bb65f0d9c.png">

**Comment by TommyLemon** [comment]
原本应该是 PostMapping
```java
	/**获取
	 * @param request 只用String，避免encode后未decode
	 * @param session
	 * @return
	 * @see {@link RequestMethod#GET}
	 */
	@PostMapping(value = "get")
	public String get(@RequestBody String request, HttpSession session) {
		return new DemoParser(GET).setSession(session).parse(request);
	}
```

Response Header 也是 application/json
![image](https://user-images.githubusercontent.com/5738175/49591027-41e2ba80-f9a8-11e8-9b81-85145e96b842.png)

**Comment by 35924784** [comment]
谢谢，已经找到原因了。需要请求头增加如下图参数就可以了：
<img width="703" alt="default" src="https://user-images.githubusercontent.com/5801601/49623098-2b1f8080-fa07-11e8-9cb4-3495566e3b1e.png">
