### ISSUE TITLE
请增加tsl及相关https特征，请增加常用token例如jwt支持

### ISSUE THREAD

**Issue by leenux** [TommyLemon/APIJSON#56]
**具体说下**
希望改进...希望做成...希望新增...

**为什么**
https和token已经是标配了，现在开发躲不过的2个特征

**Comment by TommyLemon** [comment]
感谢建议。
但这个不属于 APIJSON 的核心功能哦，核心的 APIJSONLibrary 是一个 ORM 库，
只负责把 JSON 解析为 SQL 以及 格式、权限、数据、结构 等校验。
APIJSONDemo 基于 SpringBoot，搜下 "SpringBoot https"，"SpringBoot jwt"等，方案有很多。
