### ISSUE TITLE
希望增加支持存储过程

### ISSUE THREAD

**Issue by chaojidachanmao** [TommyLemon/APIJSON#57]
希望未来能支持存储过程
现在公司的一些老系统存在大量的存储过程, 重构困难, 而且数据迁移困难

**Comment by TommyLemon** [comment]
考虑支持，可能协议是
```js
"@returnKey()": "procedureFunction(arg0,arg1,...)" //和 远程函数 类似，key 前面多了 @，支持 -,+ 设置执行顺序
```
或
```js
"@call": "procedureFunction(arg0,arg1,...)"
```

**Comment by TommyLemon** [comment]
感谢建议，已完成
"@returnKey()": "procedureFunction(arg0,arg1,...)" //和 远程函数 类似，key 前面多了 @，支持 -,+ 设置 相对于普通 SQL 的执行顺序
https://github.com/TommyLemon/APIJSON/commit/efb1dd6d543b319292a1b942019d29dfcb2a2509
