### ISSUE TITLE
希望增加数据加密功能

### ISSUE THREAD

**Issue by chaojidachanmao** [TommyLemon/APIJSON#58]
希望新增数据加密功能
我们的软件需要通过第三方的测试,但是第三方其实水平很水,但是必须测试才能上线
希望能生产模式能设定加密key 保证前端依据key加密后发送,后端依据解密

**Comment by TommyLemon** [comment]
这个不属于 APIJSON 的核心功能哦，APIJSONLibrary 只负责把 JSON 解析为 SQL 以及 格式、权限、数据、结构 等校验。
APIJSONDemo 基于 SpringBoot，搜下  "SpringBoot 加密"，方案有很多。
