### ISSUE TITLE
demo提供测试的mysql文件能合并成一个吗

### ISSUE THREAD

**Issue by chaojidachanmao** [TommyLemon/APIJSON#61]
mysql文件夹下面的sql一个个的执行实在闹心建议合并成一个

**Comment by TommyLemon** [comment]
命令行一个个 source 确实麻烦，如果能用 MySQLWorkbench, Navicat, DataGrip 等工具的话建议用工具批量导入。
至于合并成一个，确实是好建议，我找找办法吧

**Comment by TommyLemon** [comment]
已合并
https://github.com/TommyLemon/APIJSON/blob/master/MySQL/apijson_all_mysql.sql
