### ISSUE TITLE
查询数据库元数据

### ISSUE THREAD

**Issue by Onesimu** [TommyLemon/APIJSON#71]
现在的系统里怎么样可以查询到一些数据表和字段的元数据呢 比如字段名称 类型 备注等等 在前端应用中需要这些信息做一些处理

**Comment by TommyLemon** [comment]
打开
http://apijson.org/
打开控制台，然后刷新就能看到了，右侧上滑出来的文档（数据字典）就是你要的，

![image](https://user-images.githubusercontent.com/5738175/52988118-f84b2d00-3438-11e9-9aa3-353f936f0ebb.png)

在 Network 里可以看到发送了这样的请求
http://apijson.cn:8080/get
```js
{
    "[]": {
        "count": 0,
        "Table": {
            "table_schema": "sys",
            "table_type": "BASE TABLE",  //过滤非业务表
            "table_name!$": [  //过滤非业务表
                "\\_%",
                "sys\\_%",
                "system\\_%"
            ],
            "@order": "table_name+",
            "@column": "table_name,table_comment"
        },
        "Column[]": {
            "count": 0,
            "Column": {
                "table_schema": "sys",
                "table_name@": "[]/Table/table_name",
                "@column": "column_name,column_type,column_comment"
            }
        }
    }
}
```

**Comment by TommyLemon** [comment]
https://github.com/TommyLemon/APIJSON/issues/67
这个链接有说明 Request, Document, Function,  Access 表对应生成的文档

**Comment by Onesimu** [comment]
求助 最新的3.4.9版本这个元数据查不出来了 如果把DemoSQLConfig的getSchema改为空字符串, 就可以查出来, 但是数据就查不出来了 反之则是能查到表数据, 查不到元数据 说是找不到Tables表

**Comment by TommyLemon** [comment]
@Onesimu 具体报错发下哦，可以是接口返回的错误信息，或者 APIJSON Server 控制台日志，都有就最好了
