### ISSUE TITLE
获取用户及其动态的请求疑问

### ISSUE THREAD

**Issue by gsoyond** [TommyLemon/APIJSON#75]
在试用自动化工具http://apijson.org时输入如下请求，得到的只有User表信息，Comment无内容。
期望是得到用户以及用户的评论信息，是否请求构造有误？
`{
    "User[]": {
        "User": {},
        "Comment[]": {
            "Comment": {
                "userId@": "User[]/User/id"
            }
        }
    }
}`

**Comment by TommyLemon** [comment]
提取了 User，Comment[] 的信息就丢了，把  User[] 改成 [] 就行。
具体看 功能符 中的 查询数组
https://github.com/TommyLemon/APIJSON/blob/master/Document.md#3.2

**Comment by gsoyond** [comment]
明白了，谢谢！
