### ISSUE TITLE
这个工具是干嘛的

### ISSUE THREAD

**Issue by bulusite** [TommyLemon/APIJSON#76]
http://apijson.org/
没看懂,掘金看到就点进来了,其他的不说,这个网址和postman好像也没多大...

**Comment by bulusite** [comment]
大概看懂了一些,感觉火了成规范就好一点了

**Comment by bulusite** [comment]
大概看了了一些,感觉火了成规范就好一点了

**Comment by bulusite** [comment]
大概看了一些,感觉火了成规范就好一点了

**Comment by TommyLemon** [comment]
https://github.com/TommyLemon/APIJSON/issues/27

**Comment by bulusite** [comment]
> #27

谢谢，希望这个可以成为行业标准

**Comment by TommyLemon** [comment]
哈哈，我也希望，参考国内其它的 5K+ Star 的个人开源项目，看趋势很可能会成为行业标准的
