### ISSUE TITLE
聚合count查询 + 列别名出现bug

### ISSUE THREAD

**Issue by dmcn180601002** [TommyLemon/APIJSON#78]
{
  "[]":{ 
	"Moment": {
	"@column":"id:idd"
	}
	,"query":2
  },"total@":"/[]/total"
}
携带以上JSON请求 localhost:8080/get，会出现问题：
![image](https://user-images.githubusercontent.com/41134807/54655032-4d8f6280-4afb-11e9-9620-3f7838b41b4b.png)

**查看日志发现聚合查询操作的sql处理有问题**
![QQ图片20190320103451](https://user-images.githubusercontent.com/41134807/54655173-dd351100-4afb-11e9-81c5-8dd051497472.png)

**Comment by TommyLemon** [comment]
感谢反馈。
待解决：
在 AbstractSQLConfig.getColumnString 方法中，
判断是 HEAD 方法，应该在 511 行
```java
			return SQL.count(column != null && column.size() == 1 ? getKey(column.get(0)) : "*");
```
改为
```java
			return SQL.count(column != null && column.size() == 1 ? getKey(Pair.parseEntry(column.get(0), true).getKey()) : "*");
```
这样生成的就是 
SELECT count(`id`) AS count ...
了

**Comment by TommyLemon** [comment]
已解决
https://github.com/TommyLemon/APIJSON/commit/791f19b572299fe7de36a8836f304d2c20b42002
