### ISSUE TITLE
Readme 和项目 LICENSE 文件不一致

### ISSUE THREAD

**Issue by xxyuk** [TommyLemon/APIJSON#82]
**问题描述**

Readme 里说使用 996 开源协议 但是项目的协议文件仍然是 Apache 协议

**预期效果**

使用 996 开源协议

**Comment by TommyLemon** [comment]
排在前面的 12 个项目，只有 4 个加了 996 License，
剩下 MybatisPlus 等 8 个项目都只是添加了 996 证书链接而没有对应的文件，
后面 13K Star 的 WxJava 也只是添加了链接没有 996 License 文件。

**Comment by MarkoCen** [comment]
哎，既然没想好为什么要草率换License呢，License其实是个很严肃的东西

**Comment by TommyLemon** [comment]
@MarkoCen 感谢提醒
