### ISSUE TITLE
是什么原因让你取消了996ICU 协议

### ISSUE THREAD

**Issue by zengming00** [TommyLemon/APIJSON#83]
我观察到你的项目可能是使用996ICU 协议的项目中star最多的一个，但是11个小时前你又取消了
https://github.com/996icu/996.ICU/commit/42da6957325c8aaa01f577493b5d004ecdebc2bb#diff-93476254a9d4b40c36c7ebabb40d0bad
其实我也觉得突然变更协议不妥，所以我的项目决定先声明将要使用反996许可证，一年后才正式变更

**Comment by TommyLemon** [comment]
唉，一言难尽，具体见
https://github.com/TommyLemon/APIJSON/issues/82
