### ISSUE TITLE
查询条件怎么OR

### ISSUE THREAD

**Issue by dmcn180601002** [TommyLemon/APIJSON#84]
**具体说下**

![image](https://user-images.githubusercontent.com/41134807/55934994-095c3180-5c65-11e9-9438-1d57e8a0db58.png)

**像这样的，Java会处理成AND连接**

![image](https://user-images.githubusercontent.com/41134807/55943064-66151780-5c78-11e9-97a3-fb3846023bfd.png)

**Comment by TommyLemon** [comment]
@combine
https://github.com/TommyLemon/APIJSON/blob/master/Document.md#3.2
