### ISSUE TITLE
Java demo查询列表返回结果与不合期望

### ISSUE THREAD

**Issue by a1369521908** [TommyLemon/APIJSON#86]
**环境信息**
 - 系统: 
 - JDK: 
 - 数据库: 
 - APIJSON:  

**问题描述**
按照条件查询数据库的数据列表不符合期望,希望大哥能解答下是我使用方式不对还是没看好文档

参考文档:
>>>>>>>>>>>>>>>>>>
https://github.com/TommyLemon/APIJSON/blob/master/%E8%AF%A6%E7%BB%86%E7%9A%84%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3.md
>>>>>>>>>>>>>>>>>>
参考文档内容:
>>>>>>>>>>>>>>>>>>
{
  "[]": {
      "Moment":{
        "@column":"id,date,content,praiseUserIdList"
      },
    "query": 2
  },
  "total@":"/[]/total"
}
>>>>>>>>>>>>>>>>>>

我的查询结构语句:
>>>>>>>>>>>>>>>>>>
{
    "[]": {
        "Moment": {
            "userId": 82002
        },
        "query": 2
    },
    "total@": "/[]/total"
}
>>>>>>>>>>>>>>>>>>

返回结果:
>>>>>>>>>>>>>>>>>>
{
    "[]":Array[10],
    "total":11,
    "code":200,
    "msg":"success"
}
>>>>>>>>>>>>>>>>>>

期望结果:
>>>>>>>>>>>>>>>>>>
{
    "[]":Array[11],
    "total":11,
    "code":200,
    "msg":"success"
}
>>>>>>>>>>>>>>>>>>
**错误信息**

无

**Comment by TommyLemon** [comment]
默认分页，count默认用 getQueryCount return MAX_QUERY_COUNT = 10

**Comment by a1369521908** [comment]
ok,感谢解答 : )
