### ISSUE TITLE
无法发送请求，发送请求置灰

### ISSUE THREAD

**Issue by shengqiang025210** [TommyLemon/APIJSON#87]
有同志遇到过这种情况吗？一天都好好的，突然成这样了。本地和官网都是这个样子
![image](https://user-images.githubusercontent.com/40913194/56804151-56d8c100-6857-11e9-9380-6a3675eae5cd.png)
加载完就成这样了：
![image](https://user-images.githubusercontent.com/40913194/56804177-6bb55480-6857-11e9-8790-9ac3e02dfc3d.png)

**Comment by TommyLemon** [comment]
一般是网络问题，Axios 包在国外服务器，有时候下载不下来，需要翻墙后再刷新网页
