### ISSUE TITLE
新增条目的时候id怎么从外部指定，现在id生成规则是怎样的

### ISSUE THREAD

**Issue by iuhl** [TommyLemon/APIJSON#88]
感谢解答

**Comment by TommyLemon** [comment]
引用赋值，就是指定外键关系
https://github.com/TommyLemon/APIJSON/blob/master/Document.md#3.2

**Comment by TommyLemon** [comment]
生成规则默认是当前时间毫秒值，可以自定义
[AbstractSQLConfig](https://github.com/TommyLemon/APIJSON/blob/6738c6e578f732bd9248b87427ea1f3f3f7d8f3f/APIJSON-Java-Server/APIJSONORM/src/main/java/zuo/biao/apijson/server/AbstractSQLConfig.java)$SimpleCallback.newId

**Comment by iuhl** [comment]
好的 看到了 还有三个问题请教一下 
1：
![image](https://user-images.githubusercontent.com/29973384/56886785-5a13bd00-6aa2-11e9-863b-97d478288e4a.png)
![image](https://user-images.githubusercontent.com/29973384/56886838-82032080-6aa2-11e9-8aef-8301cf32398f.png)
对应到文档名称就变了   我model映射的是TestOne，试了创建其他的也是这种情况 没有前缀，
2：字段映射有方法吗  
3：确定一下哪些是基础表，哪些是demo表
![image](https://user-images.githubusercontent.com/29973384/56887169-706e4880-6aa3-11e9-85d3-874a8d0ebbc6.png)

**Comment by TommyLemon** [comment]
APIJSONAuto 自动取 _ 分隔的最后一个单词

**Comment by TommyLemon** [comment]
2.可以在 DemoSQLConfig 重写相关方法 AbstractSQLConfig.getKey，自己实现
3.[apijson/server/model](https://github.com/TommyLemon/APIJSON/tree/master/APIJSON-Java-Server/APIJSONORM/src/main/java/zuo/biao/apijson/server/model) 包里的类对应的都是基础表，其中 Table, Column, PgClass, PgAttribute 对应 MySQL 和 PostgreSQL 的系统表，
可以在 [AbstractSQLConfig](https://github.com/TommyLemon/APIJSON/blob/master/APIJSON-Java-Server/APIJSONORM/src/main/java/zuo/biao/apijson/server/AbstractSQLConfig.java) 的表映射配置里看到
